fn main() {
    // --- Git build ID ---
    let count = run("git", &["rev-list", "--count", "HEAD"]);
    let hash = run("git", &["rev-parse", "--short", "HEAD"]);
    let dirty = !run("git", &["status", "--porcelain"]).is_empty();

    let build_id = match (count.as_str(), hash.as_str()) {
        ("", _) | (_, "") => "dev".to_string(),
        (n, h) => {
            if dirty {
                format!("{n}.{h}-dirty")
            } else {
                format!("{n}.{h}")
            }
        }
    };
    println!("cargo:rustc-env=BUILD_ID={build_id}");

    // --- Build timestamp (UTC), reproducible ---
    // Source the timestamp deterministically so the SAME commit builds the SAME bytes:
    //   1. SOURCE_DATE_EPOCH (reproducible-builds.org convention; CI/packagers set it),
    //   2. else the HEAD commit's committer time (ties the date to the commit),
    //   3. else wall-clock (only for a git-less build; not reproducible, a last resort).
    // Uniqueness-per-source-change comes from BUILD_ID (commit hash + -dirty) and the
    // compiled code itself, NOT this label — so pinning the date to the commit is exactly
    // what lets a third party rebuild a tag and get a byte-identical exe to verify.
    println!("cargo:rerun-if-env-changed=SOURCE_DATE_EPOCH");
    let epoch = std::env::var("SOURCE_DATE_EPOCH")
        .ok()
        .and_then(|s| s.trim().parse::<u64>().ok())
        .or_else(|| {
            run("git", &["log", "-1", "--format=%ct"])
                .parse::<u64>()
                .ok()
        })
        .unwrap_or_else(|| {
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap_or_default()
                .as_secs()
        });
    let (y, mo, d, hh, mm, ss) = epoch_to_utc(epoch);
    let build_date = format!("{y:04}{mo:02}{d:02}.{hh:02}{mm:02}{ss:02}");
    println!("cargo:rustc-env=BUILD_DATE={build_date}");

    // --- PDB sidecar basename ---
    // The MSVC linker names the PDB after the crate (hp_thermal.pdb); embed the
    // package basename instead (hp-thermal.pdb) so the shipped exe and pdb basenames
    // agree. Derived from CARGO_PKG_NAME — no duplicated literal. /PDBALTPATH also
    // strips the absolute build path from the exe's debug directory (path hygiene +
    // reproducibility). https://learn.microsoft.com/cpp/build/reference/pdbaltpath
    println!(
        "cargo:rustc-link-arg-bins=/PDBALTPATH:{}.pdb",
        env("CARGO_PKG_NAME")
    );

    // --- Parse version from Cargo.toml ---
    let version = env("CARGO_PKG_VERSION");
    let parts: Vec<&str> = version.split('.').collect();
    let major = parts.first().unwrap_or(&"0");
    let minor = parts.get(1).unwrap_or(&"0");
    let patch = parts.get(2).unwrap_or(&"0");

    let build_num = count.parse::<u16>().unwrap_or(0);
    let full_version = format!("{version}+{build_id}");
    let description = ascii_safe(&env("CARGO_PKG_DESCRIPTION"));
    let authors = ascii_safe(&env("CARGO_PKG_AUTHORS"));
    let repository = ascii_safe(&env("CARGO_PKG_REPOSITORY"));
    let license = ascii_safe(&env("CARGO_PKG_LICENSE"));

    // Version-resource identity strings. These carry the author's name IN THE BINARY
    // (File > Properties > Details) and -- via FileDescription -- in the UAC consent
    // dialog's app-name line. This is a human-readable CLAIM only: unsigned, Windows
    // still shows "Publisher: Unknown"; cryptographic proof is Authenticode/SLSA
    // provenance. Use "(C)" not the Unicode (c) glyph -- the .rc stays ASCII.
    let author = authors
        .split('<')
        .next()
        .unwrap_or(&authors)
        .trim()
        .to_string();
    let product = "HP Thermal Control";
    let file_description = format!("{product} by {author}");
    let legal_copyright = format!("(C) {y} {author}. {license} License.");

    // --- Generate .rc with VERSIONINFO + manifest ---
    let manifest_path = std::path::Path::new(&env("CARGO_MANIFEST_DIR"))
        .join("app.manifest")
        .to_string_lossy()
        .replace('\\', "\\\\");

    let rc = format!(
        r#"// Auto-generated by build.rs — do not edit
#include <winver.h>
#include <winresrc.h>

// Application manifest (ComCtl32 v6, DPI awareness)
1 24 "{manifest_path}"

// Executable metadata — shows in Properties, Task Manager, UAC dialog
1 VERSIONINFO
FILEVERSION {major},{minor},{patch},{build_num}
PRODUCTVERSION {major},{minor},{patch},{build_num}
FILEFLAGSMASK VS_FFI_FILEFLAGSMASK
FILEFLAGS 0
FILEOS VOS__WINDOWS32
FILETYPE VFT_APP
BEGIN
    BLOCK "StringFileInfo"
    BEGIN
        BLOCK "040904B0"
        BEGIN
            VALUE "Comments", "{description} - {repository}\0"
            VALUE "CompanyName", "{author}\0"
            VALUE "FileDescription", "{file_description}\0"
            VALUE "FileVersion", "{full_version}\0"
            VALUE "InternalName", "hp-thermal\0"
            VALUE "LegalCopyright", "{legal_copyright}\0"
            VALUE "OriginalFilename", "hp-thermal.exe\0"
            VALUE "ProductName", "{product}\0"
            VALUE "ProductVersion", "{full_version} ({build_date})\0"
        END
    END
    BLOCK "VarFileInfo"
    BEGIN
        VALUE "Translation", 0x0409, 1200
    END
END

// Onboarding dialog (prototype) — laid out in dialog units. The dialog manager
// scales these to the font/DPI, so no pixel or fitting math is needed in code.
100 DIALOGEX 0, 0, 176, 139
STYLE DS_SETFONT | DS_MODALFRAME | DS_CENTER | WS_POPUP | WS_CAPTION | WS_SYSMENU
CAPTION "Install {product}"
FONT 9, "Segoe UI", 400, 0, 0x1
BEGIN
    LTEXT           "Required:",-1,7,7,120,9
    CONTROL         "SYSTEM service, started at boot",1011,"Button",BS_CHECKBOX | WS_CHILD | WS_VISIBLE,12,18,157,10
    CONTROL         "Installed to Program Files (admin-only)",1012,"Button",BS_CHECKBOX | WS_CHILD | WS_VISIBLE,12,30,157,10
    CONTROL         "Uninstall entry (Settings > Apps)",1013,"Button",BS_CHECKBOX | WS_CHILD | WS_VISIBLE,12,42,157,10
    LTEXT           "Optional:",-1,7,56,120,9
    AUTOCHECKBOX    "Run the tray at logon",1001,12,67,157,10
    AUTOCHECKBOX    "Start Menu shortcut",1002,12,79,157,10
    AUTOCHECKBOX    "Desktop shortcut",1003,12,91,157,10
    RTEXT           "",1020,7,106,162,9
    DEFPUSHBUTTON   "Install",1,65,118,50,14
    PUSHBUTTON      "Cancel",2,119,118,50,14
END
"#
    );

    let out_dir = env("OUT_DIR");
    let rc_path = std::path::Path::new(&out_dir).join("app.rc");
    std::fs::write(&rc_path, &rc).unwrap();

    let _ = embed_resource::compile(rc_path.to_str().unwrap(), embed_resource::NONE);

    // --- Rerun triggers ---
    println!("cargo:rerun-if-changed=src/");
    println!("cargo:rerun-if-changed=app.manifest");
    for dir in &[".", ".."] {
        let git = format!("{dir}/.git");
        if std::path::Path::new(&git).exists() {
            println!("cargo:rerun-if-changed={git}/HEAD");
            println!("cargo:rerun-if-changed={git}/index");
            break;
        }
    }
}

fn env(key: &str) -> String {
    std::env::var(key).unwrap_or_default()
}

/// Replace non-ASCII chars with '?' so the .rc file stays clean for the resource compiler.
fn ascii_safe(s: &str) -> String {
    s.chars()
        .map(|c| if c.is_ascii() { c } else { '?' })
        .collect()
}

fn epoch_to_utc(secs: u64) -> (u64, u64, u64, u64, u64, u64) {
    let s = secs % 86400;
    let hh = s / 3600;
    let mm = (s % 3600) / 60;
    let ss = s % 60;
    let mut days = (secs / 86400) as i64;
    let mut y = 1970i64;
    loop {
        let ydays = if y % 4 == 0 && (y % 100 != 0 || y % 400 == 0) {
            366
        } else {
            365
        };
        if days < ydays {
            break;
        }
        days -= ydays;
        y += 1;
    }
    let leap = y % 4 == 0 && (y % 100 != 0 || y % 400 == 0);
    let mdays = [
        31,
        if leap { 29 } else { 28 },
        31,
        30,
        31,
        30,
        31,
        31,
        30,
        31,
        30,
        31,
    ];
    let mut m = 0usize;
    while m < 12 && days >= mdays[m] {
        days -= mdays[m];
        m += 1;
    }
    (y as u64, (m + 1) as u64, (days + 1) as u64, hh, mm, ss)
}

fn run(cmd: &str, args: &[&str]) -> String {
    let mut c = std::process::Command::new(cmd);
    // Harden the git calls against config-driven code execution at build time: a hostile
    // checkout's .git/config (or a poisoned global/system config) can set core.fsmonitor
    // or core.pager to run a program when git executes. Ignore system+global config and
    // blank those keys. (rev-list/rev-parse/status don't run hooks.) A PATH-planted `git`
    // stays a build-env trust assumption — build.rs + build-deps already run arbitrary
    // code at build, so that's the actual boundary.
    if cmd == "git" {
        c.env("GIT_CONFIG_NOSYSTEM", "1")
            .env(
                "GIT_CONFIG_GLOBAL",
                if cfg!(windows) { "NUL" } else { "/dev/null" },
            )
            .env("GIT_TERMINAL_PROMPT", "0")
            .args(["-c", "core.fsmonitor=", "-c", "core.pager=cat"]);
    }
    c.args(args)
        .output()
        .ok()
        .filter(|o| o.status.success())
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .unwrap_or_default()
}
