fn main() {
    // --- Git build ID ---
    let count = run("git", &["rev-list", "--count", "HEAD"]);
    let hash = run("git", &["rev-parse", "--short", "HEAD"]);
    let dirty = !run("git", &["status", "--porcelain"]).is_empty();

    let build_id = match (count.as_str(), hash.as_str()) {
        ("", _) | (_, "") => "dev".to_string(),
        (n, h) => {
            if dirty {
                format!("{n}.{h}-dirty")
            } else {
                format!("{n}.{h}")
            }
        }
    };
    println!("cargo:rustc-env=BUILD_ID={build_id}");

    // --- Build timestamp (UTC) ---
    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default();
    let (y, mo, d, hh, mm, ss) = epoch_to_utc(now.as_secs());
    let build_date = format!("{y:04}{mo:02}{d:02}.{hh:02}{mm:02}{ss:02}");
    println!("cargo:rustc-env=BUILD_DATE={build_date}");

    // --- Parse version from Cargo.toml ---
    let version = env("CARGO_PKG_VERSION");
    let parts: Vec<&str> = version.split('.').collect();
    let major = parts.first().unwrap_or(&"0");
    let minor = parts.get(1).unwrap_or(&"0");
    let patch = parts.get(2).unwrap_or(&"0");

    let build_num = count.parse::<u16>().unwrap_or(0);
    let full_version = format!("{version}+{build_id}");
    let description = ascii_safe(&env("CARGO_PKG_DESCRIPTION"));
    let authors = ascii_safe(&env("CARGO_PKG_AUTHORS"));
    let repository = ascii_safe(&env("CARGO_PKG_REPOSITORY"));
    let license = ascii_safe(&env("CARGO_PKG_LICENSE"));

    // --- Generate .rc with VERSIONINFO + manifest ---
    let manifest_path = std::path::Path::new(&env("CARGO_MANIFEST_DIR"))
        .join("app.manifest")
        .to_string_lossy()
        .replace('\\', "\\\\");

    let rc = format!(
        r#"// Auto-generated by build.rs — do not edit
#include <winver.h>

// Application manifest (ComCtl32 v6, DPI awareness)
1 24 "{manifest_path}"

// Executable metadata — shows in Properties, Task Manager, UAC dialog
1 VERSIONINFO
FILEVERSION {major},{minor},{patch},{build_num}
PRODUCTVERSION {major},{minor},{patch},{build_num}
FILEFLAGSMASK VS_FFI_FILEFLAGSMASK
FILEFLAGS 0
FILEOS VOS__WINDOWS32
FILETYPE VFT_APP
BEGIN
    BLOCK "StringFileInfo"
    BEGIN
        BLOCK "040904B0"
        BEGIN
            VALUE "Comments", "{repository}\0"
            VALUE "CompanyName", "{authors}\0"
            VALUE "FileDescription", "{description}\0"
            VALUE "FileVersion", "{full_version}\0"
            VALUE "InternalName", "hp-thermal\0"
            VALUE "LegalCopyright", "{license}\0"
            VALUE "OriginalFilename", "hp-thermal.exe\0"
            VALUE "ProductName", "HP Thermal Control\0"
            VALUE "ProductVersion", "{full_version} ({build_date})\0"
        END
    END
    BLOCK "VarFileInfo"
    BEGIN
        VALUE "Translation", 0x0409, 1200
    END
END
"#
    );

    let out_dir = env("OUT_DIR");
    let rc_path = std::path::Path::new(&out_dir).join("app.rc");
    std::fs::write(&rc_path, &rc).unwrap();

    let _ = embed_resource::compile(rc_path.to_str().unwrap(), embed_resource::NONE);

    // --- Rerun triggers ---
    println!("cargo:rerun-if-changed=src/");
    println!("cargo:rerun-if-changed=app.manifest");
    for dir in &[".", ".."] {
        let git = format!("{dir}/.git");
        if std::path::Path::new(&git).exists() {
            println!("cargo:rerun-if-changed={git}/HEAD");
            println!("cargo:rerun-if-changed={git}/index");
            break;
        }
    }
}

fn env(key: &str) -> String {
    std::env::var(key).unwrap_or_default()
}

/// Replace non-ASCII chars with '?' so the .rc file stays clean for the resource compiler.
fn ascii_safe(s: &str) -> String {
    s.chars()
        .map(|c| if c.is_ascii() { c } else { '?' })
        .collect()
}

fn epoch_to_utc(secs: u64) -> (u64, u64, u64, u64, u64, u64) {
    let s = secs % 86400;
    let hh = s / 3600;
    let mm = (s % 3600) / 60;
    let ss = s % 60;
    let mut days = (secs / 86400) as i64;
    let mut y = 1970i64;
    loop {
        let ydays = if y % 4 == 0 && (y % 100 != 0 || y % 400 == 0) {
            366
        } else {
            365
        };
        if days < ydays {
            break;
        }
        days -= ydays;
        y += 1;
    }
    let leap = y % 4 == 0 && (y % 100 != 0 || y % 400 == 0);
    let mdays = [
        31,
        if leap { 29 } else { 28 },
        31,
        30,
        31,
        30,
        31,
        31,
        30,
        31,
        30,
        31,
    ];
    let mut m = 0usize;
    while m < 12 && days >= mdays[m] {
        days -= mdays[m];
        m += 1;
    }
    (y as u64, (m + 1) as u64, (days + 1) as u64, hh, mm, ss)
}

fn run(cmd: &str, args: &[&str]) -> String {
    std::process::Command::new(cmd)
        .args(args)
        .output()
        .ok()
        .filter(|o| o.status.success())
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .unwrap_or_default()
}
